services:
  directus:
    image: directus/directus:11.3.4
    environment:
      # Secret Keys & Env
      - KEY=zrb96IdBbzRRbqMiKuVikbrdjfiScfDv
      - SECRET=TIW3FeNSQrcWsTvbtyMop26SnjOwanQN
      - APP_ENV=production
      - ADMIN_EMAIL=spsystems.ia@gmail.com # Atualize
      - ADMIN_PASSWORD=Sps2025dir # Atualize
      - PUBLIC_URL=https://app.spsystems.pro # Atualize

      ## 17/03/2025 Correcao para nao sair do directus e dar erro de Cookies
      - AUTH_TOKEN_EXPIRY=30d
      - REFRESH_TOKEN_EXPIRY=30d
      - REFRESH_TOKEN_COOKIE_SECURE=false
      - REFRESH_TOKEN_COOKIE_SAME_SITE=lax
      - ACCESS_TOKEN_TTL=144000m
      - SESSION_COOKIE_TTL=30d

      # Dados SMTP
      #- EMAIL_TRANSPORT=smtp
      #- EMAIL_SMTP_USER=example@smtp.com # Atualize
      #- EMAIL_SMTP_PASSWORD=senha_smtp # Atualize
      #- EMAIL_SMTP_HOST=smtp-relay.brevo.com # Para outro Host, atualize 
      #- EMAIL_SMTP_PORT=587
      #- EMAIL_SMTP_IGNORE_TLS=true
      #- EMAIL_FROM=from@example.com # Atualize
      #- EMAIL_SMTP_SECURE=false
      #- EMAIL_VERIFY_SETUP=true

      # Dados MinIO
      - STORAGE_LOCATIONS=s3
      - STORAGE_S3_DRIVER=s3 
      - STORAGE_S3_KEY=directus
      - STORAGE_S3_SECRET=TgO5EFAhidunYdhwwCPpHWMGRncgpGzGSGJVBWUM # Atualize
      - STORAGE_S3_BUCKET=directus
      - STORAGE_S3_REGION=us-east-1
      - STORAGE_S3_ENDPOINT=s3.spsystems.pro # Atualize
      - STORAGE_S3_FORCE_PATH_STYLE=true

      # Redis
      - CACHE_ENABLED=false
      - CACHE_STORE=redis
      - CACHE_AUTO_PURGE=true
      - REDIS=redis://redis:6379/8

      # Dados Postgres
      - DB_CLIENT=pg
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=directus
      - DB_USER=postgres
      - DB_PASSWORD=Sps2025pos # Atualize
      
      # Cors
      - CORS_ENABLED=true
      - CORS_ORIGIN=true
      - CORS_METHODS=GET,POST,PATCH,DELETE
    volumes:
      - extensions:/directus/extensions
      - templates:/directus/templates
 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        traefik.enable: "true"
        traefik.http.routers.directus.service: "directus"
        traefik.http.routers.directus.rule: "Host(`app.spsystems.pro`)" # Atualize
        traefik.http.services.directus.loadbalancer.server.port: "8055"
        traefik.http.routers.directus.entrypoints: "websecure"
        traefik.http.routers.directus.tls.certresolver: "le"
    networks:
      - externa
      - interna
volumes:
  extensions:
  templates:
  
networks:
  interna:
    external: true
  externa:
    external: true