x-variaveis: 
  &variaveis
    DB_TYPE: postgresdb
    DB_POSTGRESDB_PORT: 5432
    DB_POSTGRESDB_HOST: postgres
    DB_POSTGRESDB_DATABASE: n8n
    DB_POSTGRESDB_USER: postgres
    DB_POSTGRESDB_PASSWORD: Sps2025pos # Atualize

    ## novas variáveis implementadas 25/03/2025
    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
    N8N_RUNNERS_ENABLED: "false"
    N8N_RUNNERS_MODE: "internal"
    OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: "false"
    N8N_NODE_PATH: "/home/node/.n8n/nodes"
    
    # Configs do frontend e webhook
    N8N_HOST: edt.spsystems.pro # Atualize
    WEBHOOK_URL: https://whk.spsystems.pro/ # Atualize
    N8N_EDITOR_BASE_URL: https://edt.spsystems.pro/ # Atualize
    N8N_PROTOCOL: https
    
    # Configurações da fila (Redis worker)
    NODE_ENV: production
    N8N_ENCRYPTION_KEY: "noJbC3oLKzSGXEyRNtV0DoiQmK5zBG83" # Atualize
    EXECUTIONS_MODE: queue
    QUEUE_BULL_REDIS_HOST: redis
    QUEUE_BULL_REDIS_PORT: 6379
    QUEUE_BULL_REDIS_DB: 5
    
    # Armazenamento S3
    N8N_EXTERNAL_STORAGE_S3_HOST: s3.spsolutions.pro # Atualize
    N8N_EXTERNAL_STORAGE_S3_BUCKET_NAME: n8n 
    N8N_EXTERNAL_STORAGE_S3_BUCKET_REGION: eu-south 
    N8N_EXTERNAL_STORAGE_S3_ACCESS_KEY: n8n
    N8N_EXTERNAL_STORAGE_S3_ACCESS_SECRET: KXy1wJ1e8JEPer3e2lJq8sAcJ0KtyDkbAN8tbUIa # Atualize
    
    # Email
    #N8N_EMAIL_MODE: smtp
    #N8N_SMTP_HOST: smtp-relay.brevo.com # Para outro Host, atualize
    #N8N_SMTP_USER: example@smtp.com # Atualize
    #N8N_SMTP_PASS: senha_smtp # Atualize
    #N8N_SMTP_SENDER: Nome-de-Exibição <example@example.com> # Atualize
    #N8N_SMTP_PORT: 587
    #N8N_SMTP_SSL: "false" # Se a porta for 465 = true | Se a porta for 587 = false
    
    # Configuração Langfuse
    LANGCHAIN_ENDPOINT: "https://api.smith.langchain.com"
    LANGCHAIN_TRACING_V2: "true"
    LANGCHAIN_API_KEY: sua_langfuse_api_key # Atualize

    # Configs de Compatibilidade 
    NODE_FUNCTION_ALLOW_EXTERNAL: "*"
    NODE_FUNCTION_ALLOW_BUILTIN: "*"
    N8N_PAYLOAD_SIZE_MAX: 512
    EXECUTIONS_DATA_PRUNE: "true"
    EXECUTIONS_DATA_MAX_AGE: 336
    N8N_COMMUNITY_PACKAGES_ENABLED: "true"
    N8N_REINSTALL_MISSING_PACKAGES: "true"
    GENERIC_TIMEZONE: "America/Sao_Paulo"
    EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS: "true"
    EXECUTIONS_DATA_SAVE_ON_PROGRESS: "all"
    
services: 
  n8n_editor: 
    image: n8nio/n8n:latest
    environment: 
      <<: *variaveis
    deploy: 
      mode: replicated
      replicas: 1
      placement: 
        constraints: 
          - node.role == manager
      resources:
        limits:
          cpus: '2'
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.n8n_editor.rule=Host(`edt.spsystems.pro`) # Atualize
        - traefik.http.routers.n8n_editor.service=n8n_editor
        - traefik.http.routers.n8n_editor.entrypoints=websecure
        - traefik.http.routers.n8n_editor.tls.certresolver=le
        - traefik.http.routers.n8n_editor.tls=true
        - traefik.http.services.n8n_editor.loadbalancer.server.port=5678
    networks:
      - traefik_public
      - app_network

  n8n_webhook:
    image: n8nio/n8n:latest
    command: webhook
    environment:
      <<: *variaveis
    deploy:
      mode: replicated
      # pode criar replicas
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '2'
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.n8n_webhook.rule=Host(`whk.spsystems.pro`) # Atualize
        - traefik.http.routers.n8n_webhook.service=n8n_webhook
        - traefik.http.routers.n8n_webhook.entrypoints=websecure
        - traefik.http.routers.n8n_webhook.tls.certresolver=le
        - traefik.http.routers.n8n_webhook.tls=true
        - traefik.http.services.n8n_webhook.loadbalancer.server.port=5678
    networks:
      - traefik_public
      - app_network

  n8n_worker:
    image: n8nio/n8n:latest
    command: worker --concurrency=150
    environment:
      <<: *variaveis
    deploy:
      mode: replicated
      # pode criar replicas
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '2'
          memory: 1548M
    networks:
      - traefik_public
      - app_network

volumes:
  n8n-custom-nodes:

networks:
  traefik_public:
    external: true
    name: externa
  app_network:
    external: true
    name: interna